version: "3"
services:
  controlcenter:
    image: control-center
    restart: unless-stopped
    ports:
      - '80:8001'  
  dwdfeed:
    image: cap-feed-fetcher-service
    restart: unless-stopped
    environment: 
      FEED_URL: https://www.dwd.de/DWD/warnungen/cap-feed/de/atom.xml
      KAFKA_HOST: kafka:9092
      WARNING_DISTRIBUTION_URL: http://warningdistributionservice:9101/api/v1/alerts
      PULL_INTERVAL: 8000
      REDIS_HOST: redis
    ports:
      - "9301:9301"
  inatewsfeed:
    image: cap-feed-fetcher-service
    restart: unless-stopped
    environment: 
      FEED_URL: https://inatews.bmkg.go.id/rss/capatomlast40event.xml
      KAFKA_HOST: kafka:9092
      WARNING_DISTRIBUTION_URL: http://warningdistributionservice:9101/api/v1/alerts
      PULL_INTERVAL: 8000
      REDIS_HOST: redis
    ports:
      - "9302:9301"     
  meteoinfofeed:
    image: cap-feed-fetcher-service
    restart: unless-stopped
    environment: 
      FEED_URL: https://meteoinfo.ru/hmc-output/cap/cap-feed/en/atom.xml
      KAFKA_HOST: kafka:9092
      WARNING_DISTRIBUTION_URL: http://warningdistributionservice:9101/api/v1/alerts
      PULL_INTERVAL: 20000
      REDIS_HOST: redis
    ports:
      - "9303:9301"           
  redis:
    image: "redis:alpine"
    restart: unless-stopped      
  warningdistributionservice:
    image: warning-distribution-service
    restart: unless-stopped
    ports:
      - "9101:9101"
    environment: 
      KAFKA_HOST: kafka:9092          
  webdisseminator:
    image: web-disseminator
    restart: unless-stopped
    ports:
      - "9201:9201"       
    environment: 
      KAFKA_HOST: kafka:9092    
  zookeeper:
    image: confluent/zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: birds:1:1, alert:1:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock