version: "3"
services:
  controlcenter:
    image: control-center
    ports:
      - '80:8001'
  dummy:
    image: dummy-service
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - alertnet
  warningdistributionservice:
    image: warning-distribution-service
    restart: unless-stopped
    networks:
      - alertnet
  redis:
    image: "redis:alpine"
    restart: unless-stopped
    networks:
      - alertnet
  zookeeper:
    image: confluent/zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_DELETE_TOPIC_ENABLE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - ZK_HOSTS=zookeeper:2181
      - APPLICATION_SECRET=random-secret
      - KM_ARGS=-Djava.net.preferIPv4Stack=true
    command: -Dpidfile.path=/dev/nul
networks:
  alertnet:
